# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Current Time
        uses: 1466587594/get-current-time@v2.0.0
        id: current-time
        with:
          format: MM/DD/YYYY HH:mm

      - name: Set current time as environmental variable
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: |
          echo "::set-env name=F_TIME::${{ steps.current-time.outputs.formattedTime }}"
          echo "::set-env name=TIME::${{ steps.current-time.outputs.time }}"
          echo $TIME
          echo $F_TIME
          echo "MODFLOW 6 examples: built at ${F_TIME}"

      - name: create bodyFile
        shell: bash
        run: |
          echo "MODFLOW 6 examples -- built "${F_TIME} > bodyFile
          cat bodyFile
