# This is a basic workflow to help you get started with Actions

name: macos-test-gfortran

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install gfortran (macOS)
      run: |
        brew cask info gfortran
        brew cask install gfortran
        sudo ln -fs /usr/bin/gfortran-8 /usr/local/bin/gfortran
    
    - name: Print gfortran version
      run: |
        gfortran --version
