# This is a basic workflow to help you get started with Actions

name: Miniconda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  miniconda-test:
    name: autotests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.7, 3.6]
        os: [ubuntu-latest, macos-latest, windows-latest]
        file-path: [etc]
        cmd-str: [""]
        include:
          - os: ubuntu-latest
            python-version: 3.8
            file-path: .github
            cmd-str: .github
          - os: ubuntu-latest
            python-version: 3.8
            file-path: etc
            cmd-str: etc

    steps:
    # check out repo
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Cache Miniconda
      uses: actions/cache@v2.1.0
      env:
        # Increase this value to reset cache if environment.yml has changed
        CACHE_NUMBER: 1
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-python${{ matrix.python-version }}-${{ matrix.file-path }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    # Standard python fails on windows without GDAL installation
    # Using custom bash shell ("shell: bash -l {0}") with Miniconda
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: flopy
        use-only-tar-bz2: true

    - name: Determine python environment
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Add jupyter and nbconvert to one matrix entry
      if: matrix.file-path == '.github'
      shell: bash -l {0}
      run: |
        conda install -n flopy -c conda-forge jupyter nbconvert

    - name: Determine python environment
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Add packages to the environment
      shell: bash -l {0}
      run: |
        conda env update -n flopy --file etc/environment.yml

    - name: Determine python environment
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Run a command with ${{ matrix.cmd-str }}
      shell: bash -l {0}
      run: |
        ls -la ${{ matrix.cmd-str}}
